dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
notifications:
  slack:
    rooms:
      secure: XWiLuFDdBpwSTOxNJg2G5/2CcJzDu1WMs4s7E756R+RaN6YDOhAdDaUJ9s4ch/Fo2EHTRHtIgRkEn1MEgo8Te3PBSl+uGaVQAj1/DjasRQKokkWGeAMTBi26B9vBNOTDaIfo6q/ejVnwddmJqQxxmZkNtRh9brAR4g5wFhcUJTBElfDmL6cJwtakNx0XQlJuKh6kRTfIIWpokio51To9vZhwWRudZfUITZ8SNhatFDURvYh0ibIof2afhtJ5ydo2gQd1B08cNgEFyOgGGnYSVPT6u9/hzGCXMqejNdvrIHmH3HkKYXm0UcpyVd4dbnDui9dpoRjja0GD1sZJvHbo3tBYCJN96ikIACdH5rVUYeciLwFHVE071kIx+5LL/ygfX6w2XqC4jaUpyq9DFq24OaNpXQY1Ca4y9pu7IHgj4DYsIeJ7TBm55P4840kcUIDMB7WMZPzbDicK5/NtnG5HzMEUqeXHMsGIGQ9/kDZnzhZUlWaGDxazXaKJ9O+3GilaIUTvgvNlvf1QVQTua+JiswGAWqUJr7TqfnDA15Xrll0Y92WunAMzpHtlG4VPGluJifKOxrUfBjizRJ52A+R3CjvmLTgZ6JL+0oDFH5n0X4YtyCbpE80NpnXkNPV+HjH87JjnlUmPWpTDcxW3Fesif+YWV3QcGAp7Lja0Mc2ECNA=
